<?php
$app_url = '//' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']);
$app_url = str_replace("/client", "", $app_url);
$js_url = str_replace("/apps/r_support_app", "", $app_url);
header('Content-type: application/x-javascript');
$content = '(function() {var js_url = "' . $js_url . '";var e = document.createElement("div");';
echo 'document.write("<script src=\'//code.jquery.com/jquery-1.12.0.min.js\'></script><script src=\'' . $app_url . '/js/bootstrap.js\'></script><script id=\'url\' src=\'' . $app_url . '/js/support.js\' js_url=\'' . $js_url . '\'></script>");';
$js_content = '<link rel="stylesheet" type="text/css" href="' . $app_url . '/css/bootstrap.css" /><link rel="stylesheet" type="text/css" href="' . $app_url . '/css/widget.css" />';
$js_content.= '<div class="fixedbutton"><div class="dropdown dropup"><a id="js-support-ticket-button" class="btn btn-default dropdown-toggle"  href="#js-support-drop-down" title="Support" data-toggle="dropdown">Support</a><ul class="dropdown-menu-lg dropdown-menu dropdown-menu-right" id="js-support-drop-down"><li><div class="col-xs-12"><div class="show-messages"></div><form role="form" id="js-supportForm" class="form-horizontal clearfix"><h3>New Ticket</h3><div class="form-group"><label class="col-sm-3 control-label" for="name">Name</label><div class="col-sm-9"><input type="text" class="form-control" id="name" name="name" placeholder="Name" required value="" /></div></div><div class="form-group"><label class="col-sm-3 control-label" for="email">Email</label><div class="col-sm-9"><input type="text" class="form-control" id="email" name="email" placeholder="Email" required value=""></div></div><div class="form-group"><label class="col-sm-3 control-label" for="subject">Subject</label><div class="col-sm-9"><input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required value="" /></div></div><div class="form-group"><label class="col-sm-3 control-label" for="Description">Description</label><div class="col-sm-9"><textarea rows="6" id="description" name="description" placeholder="Description" class="form-control" required></textarea></div></div><div class="well well-sm clearfix"><div class="pull-right"><label class="sr-only" for="submit2">submit</label><input type="button" class="btn btn-primary btn-lg" id="js-supportSubmit" value="Submit" ></div></div></form></div></li></ul></div></div>';
$content.= 'e.innerHTML = \'' . $js_content . '\';document.body.appendChild(e);})();';
echo $content;
?>