(function() {
    var $dc = $(document);
    var session_storage_apps = JSON.parse(sessionStorage.getItem("apps"));
    $dc.ready(function() {
        $('body').append('<div class="modal fade" id="r_support_app_modal" tabindex="-1" role="dialog" aria-labelledby="loginSupportAppModalLabel" aria-hidden="false"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" id="js-support-app-close">×</span><span class="sr-only">Close</span></button><div class="media list-group-item-heading"><div class="pull-left"><img class="img-circle" width="36" height="36" src="' + session_storage_apps.r_support_app.icon + '" /></div><div class="media-body"><h4 class="modal-title" id="exampleModalLabel">' + i18next.t('Support Ticket') + '</h4><div><span class="text-muted">v' + session_storage_apps.r_support_app.version + '</span> By <a target="_blank" href="' + session_storage_apps.r_support_app.author_url + '?utm_source=restyaboard&utm_medium=apppopup&utm_campaign=rb-app-support-app-v0.1.1' + '" title="author">' + session_storage_apps.r_support_app.author + '</a></div></div></div></div><div class="modal-body import-block"><span>' + i18next.t('Help desk or support ticket system or customer service software using Restyaboard.') + '.</span><h4>' + i18next.t('How it works') + '</h4><ul><li>' + i18next.t('Embed front-end widget similar to Samanage in a website to receive tickets from customers') + '.</li><li>' + i18next.t('Tickets will be stored in TODO board and under TODO list in a card, Click here to <a title="Settings" href="#/apps/r_support_app" class="text-primary">Change Settings</a>') + '.</li></ul><div class="media-body"><img class="img-responsive" src="apps/r_support_app/img/Support-Ticket-Settings.png" /></div><ul><li>' + i18next.t('You can use kanban workflow in handling tickets') + '.</li></ul><h4>' + i18next.t('Widget') + '</h4><ul><li>' + i18next.t('Copy the code and paste it before the closing &lt;/body&gt; tag') + '.</li></ul><input type="text" readonly class="form-control" value="&lt;script type=\'text/javascript\' src=\'' + window.location.protocol + '//' + window.location.hostname + window.location.pathname + 'client/apps/r_support_app/support.php\'&gt;&lt;/script&gt;" /></div><div class="modal-footer"><a id="js-support-ticket-app-button" href="#" title="' + i18next.t('Close') + '" class="btn btn-primary">' + i18next.t('Close') + '</a></div></div></div></div>');
    });

    $dc.on('click', '#js-support-ticket-app-button', function(event) {
        $('#r_support_app_modal').modal('hide');
        $('.js-chosen-select').select2();
        return false;
    });
})();
